[package]
name = "simulation-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared-types.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
